### ISSUE TITLE
Publish to Docker Hub + update README?

### ISSUE THREAD

**Issue by vito** [cloudfoundry-community/slack-notification-resource#10]
With 0.74's support for [custom resource types](https://concourse.ci/configuring-resource-types.html) this would make this resource a lot easier to use. Similar format as the [PivNet resource](https://github.com/pivotal-cf-experimental/pivnet-resource#installing) is a good trend to follow imo.

**Comment by jhunt** [comment]
We have just finished building a concourse pipeline to manage the versions and run tests, at the Dockerhub level.  Will update README once we get an official build out the door.

**Comment by vito** [comment]
Thanks!

**Comment by jhunt** [comment]
Done (btw)

https://hub.docker.com/r/cfcommunity/slack-notification-resource/

The `latest` tag gets you latest stable.  Specific tags exist for each releases "version", and `edge` is there for those who like to live on the bleeding edge (if it breaks you get to keep *both* pieces)

**Comment by vito** [comment]
yaaaay, thanks
