### ISSUE TITLE
notify slack conditionally

### ISSUE THREAD

**Issue by HeenaBansal20** [cloudfoundry-community/slack-notification-resource#102]
HI , 
I wanted to know if we have following feature enabled in this resource.
I wanted to notify slack only at particular condition not every time when pipelines success..
For example:
I want to notify slack when my notification message  is not empty..else don't slack anything.

DO we have something like this which I can use.

Thanks

**Comment by bgandon** [comment]
Yes, indeed.
Use a `put` step, and configure it with a `text_file` in the `params`. Then when an earlier step generates the notification text in an artefact, when the text file is present but empty, then the `slack-notification` resource will not sent any notification, just [as documented](https://github.com/cloudfoundry-community/slack-notification-resource#put-step-out-script-sends-a-message-to-slack).
Don't hesitate to have a look at the docs for more possibilities.
