### ISSUE TITLE
"Notify on repeated failure" option and "Notify on recovered" 

### ISSUE THREAD

**Issue by scottschulthess** [cloudfoundry-community/slack-notification-resource#18]
So, I'm not sure how this would be possible to implement in this concourse resource, but I wanted to get the idea out there:
For builds that run on timers and notify slack, it can be really noisy unless you have the ability to turn off repeated failure notifications and you can only alert when the job starts working again "the job is back to normal!"

I have no idea how this would work in a course resource, as it requires persistence.

**Comment by jhunt** [comment]
Yeah, we would definitely need some sort of external memory, like a redis kvstore or a git resource to track history.  This is a great idea, but perhaps it requires an addon?

**Comment by xanderrman** [comment]
just wondering  if you've looked into this any further @scottschulthess

**Comment by jhunt** [comment]
Specifically, should we spin up a separate project (custom API + BOSH release) to handle this "trap"-like behavior?

**Comment by jhunt** [comment]
I've gotten more and more external requests for this type of functionality in lots of messaging systems, and I've found a need for it more and more myself.  However, I don't think it's a good fit for the way this resource is architected, so it needs to be a new project.

**Comment by attack** [comment]
I was able to replicate this requested functionality using this project and [semver-resource](https://github.com/concourse/semver-resource).  I can extract to a gist if there is interest.

**Comment by scottschulthess** [comment]
interested!

**Comment by attack** [comment]
@scottschulthess I extracted this to a [gist](https://gist.github.com/attack/239501a39d9b153229d88b65c05853a6).

This is v1, so it probably has potential for refactoring.

SemVer is used to persist data on last build status.  It increments the `patch` version on a fail, and the `minor` on success.

This example uses Slack's attachment based messaging.  The key part is that messages are always created, then the two success/failure scripts hold the logic that will clear out the messages (ie transition of fail to pass, pass to fail, etc) and create a special `text_file` that determines whether to abort sending of the slack message, or leave as is.
