### ISSUE TITLE
Support notification to multiple channels

### ISSUE THREAD

**Issue by mboldt** [cloudfoundry-community/slack-notification-resource#19]
We have a use case where we want a couple of individuals to receive slack notifications in their @user channels, but don't want to manage multiple `put`s as this is repeated throughout our pipeline at failure steps. It seems simple enough to add a `for` loop over whitespace-separated channels in `out`. I'm happy to take a shot at this and submit a PR if there's interest.

**Comment by jhunt** [comment]
Sounds good to me, go ahead and take a crack at it :)

**Comment by mboldt** [comment]
I submitted a PR #20 and would love to see it merged. Anything I can do to help?

**Comment by lnguyen** [comment]
new release cut @mboldt

**Comment by mboldt** [comment]
Awesome; thank you!
