### ISSUE TITLE
Interpolation in attachment text doesn't work

### ISSUE THREAD

**Issue by analytically** [cloudfoundry-community/slack-notification-resource#25]

**Comment by flightofthunder** [comment]
I'm having this issue too. Doing something like this:
```
attachments:
      - color: '#99ccff'
        text: |
          Build status: running
          $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
```
will output the string verbatim, whereas I would expect it to interpret the metadata variables.

**Comment by jhunt** [comment]
I will take a look at this tonight, @analytically

**Comment by analytically** [comment]
Thanks!

**Comment by shedali** [comment]
This works great - interpolation of values in the fields array would also be useful.

**Comment by jagregory** [comment]
+1 for the fields array too.
