### ISSUE TITLE
Ability to pass attachments file from concourse task to resource

### ISSUE THREAD

**Issue by jdimmerman** [cloudfoundry-community/slack-notification-resource#30]
I'd like the ability to pass information from a concourse task to this resource for use with slack attachments.  I have a change ready but need the permissions to create a new branch and submit a PR.  Can someone provide that or is this not something you would like to implement?

Thanks!
Jason

**Comment by pdelagrave** [comment]
@jdimmerman Fork the repo, create a branch in your forked repo, commit your changes in it, from there you'll be able to submit your PR to the original repo.

**Comment by jdimmerman** [comment]
Sorry for a failure in responding sooner.  Thanks @pdelagrave!  I'll do so now.

**Comment by jdimmerman** [comment]
https://github.com/cloudfoundry-community/slack-notification-resource/pull/31/commits
