### ISSUE TITLE
Be able to edit a message

### ISSUE THREAD

**Issue by Seraf** [cloudfoundry-community/slack-notification-resource#40]
Hello,

I don't know if it's possible but it could be a great feature to be able to edit a message.
My usecase: we would like to give realtime output of a deployment on slack, but having a new message each time is a bit noisy. So ideally we would create a new message when a build begin, then use this message to add attachment on it dynamically.

What do you think about it ?

Thanks !

**Comment by jhunt** [comment]
Editing messages is a great idea, but would require that someone keep state, including message IDs.  It would probably be easier and less error-prone to implement an external message gateway that happens to manipulate Slack, and then write a concourse resource that talks to that gateway.

I've actually been thinking of doing that for other reasons (like broke/fixed style messaging) but haven't been able to carve out much time.

**Comment by Seraf** [comment]
Hello,
I was thinking about this issue during my vacations, and I think it could be done by using input/output.
I mean, we could expose the answer of slack API containing the message ID and all the things necessary to edit the message.
It would allow in the same pipeline to edit the message without having to maintain a state.
Having an external service to manage that sounds a bit overkill to me.

What do you think about this ?

**Comment by jhunt** [comment]
My goal in building an external service is to encompass several notification schemes, including email / slack / sms / hipchat / flowdock / irc / etc., and provide other functionality like broke/fixed messaging, time-of-day dispatch rules (send to slack 8a-5p, sms 5p-8a), etc.
