### ISSUE TITLE
Empty text_file sends notification

### ISSUE THREAD

**Issue by enchobelezirev** [cloudfoundry-community/slack-notification-resource#81]
I have the following pipeline:
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest
- name: slack-alert
  type: slack-notification
  source:
    url: ((slack-webhook))

jobs:
- name: test
.....
  - task: example
     .....
     on_success:
          put: slack-alert
          params:
            text_file: "files/slack-notification-test"
            text: ${TEXT_FILE_CONTENT}

The file  files/slack-notification-test exists but it is empty. It is crated by the above task `example` and is populated in certain cases. I want when the file is populated with some content, then to be sent to the Slack channel. The problem is that each time I have the `(no notification provided)` message, event though the file is empty.

As the documentation says, 

> when text specified with $TEXT_FILE_CONTENT and more content, and...
text_file omitted, or present but file missing
$TEXT_FILE_CONTENT is replaced with "(no notification given)"
text_file specified and present but file empty:
no notification is sent

Is something wrong or I did something wrong?

Regards,
Encho

**Comment by jhunt** [comment]
That sounds like a bug...

**Comment by enchobelezirev** [comment]
Mistake from my side.

**Comment by samcolson4** [comment]
What was the solution to this issue?
