### ISSUE TITLE
Hints for debugging issues

### ISSUE THREAD

**Issue by professor** [cloudfoundry-community/slack-notification-resource#84]
I believe that I correctly setup this concourse job, but I'm not getting any slack notifications. Some hints in the documentation on how to debug this would be nice.

**Comment by professor** [comment]
Notes for my future self. If you get a 200 response from slack, check to see if the webhook matches the slack channel name. The webhook url is unique for the channel.

**Comment by jhunt** [comment]
I recall running into this; Slack changed their webhook scopes a few years back and we probably just need to update the README to reflect that.
