### ISSUE TITLE
[REQUEST] Make a new release

### ISSUE THREAD

**Issue by sdurrheimer** [cloudfoundry-community/slack-notification-resource#87]
First of all thanks for the useful resource.

Would it be possible to cut a new version with the latest changes?  
In my case, I particularly need the following fix: 3f2b8d4

**Comment by jhunt** [comment]
Are you using the BOSH release or the Docker image?

**Comment by sdurrheimer** [comment]
@jhunt I'm using the docker image

**Comment by jhunt** [comment]
1.6.0 tag on the Docker image is live this morning.

**Comment by sdurrheimer** [comment]
@jhunt Thank you !
