### ISSUE TITLE
Using an "@ mention" seems not to work

### ISSUE THREAD

**Issue by professor** [cloudfoundry-community/slack-notification-resource#88]
In one of our slack messages, we would like to @ mention a team. Slack seems to treat this as text, not a command. I'm wondering if there is some special syntax to use.

**Comment by jhunt** [comment]
There is, you have to do something like `<@id>`, or `<!id>`, except that `id` is an internal identifier that you only ever see when Slack itself is really slow or wonky, and isn't resolving internal identifiers to names.  We have a joke pipeline that @-interrupts a slack team every hour that uses something like this:

```
  - put: slack
    params:
      text: Help, I've fallen and can't get up, I need <!subteam^SBM1AFXYZ|someone>
```

(don't worry, that pipeline is paused until someone remembers we have it)

**Comment by professor** [comment]
I found the solution.....

"<@WPX3930123> <!subteam^S01432423921>"

The first is @messaging an individual. You can get their member id by going to their profile via slack app or web app.
The second is @messaging a group. You can get their member from the web app.

@jhunt sorry, I had this ready to go and got interrupted!

**Comment by professor** [comment]
@jhunt Do we want to put this in the readme?

**Comment by professor** [comment]
See https://github.com/cloudfoundry-community/slack-notification-resource/pull/89 for my suggestion
